# Docker - Build multiple Docker images
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acrRegistry: 'nagp2024amcart0test0acr0.azurecr.io' # Replace with your ACR name
  azureSubscriptionConnectionString: 'ServiceConnectionAmcart0Test0' # Replace with your ARM connection name

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: BuildImages
    displayName: Build Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'
      inputs:
        dockerVersion: '17.09.0-ce' # Consider using a newer version
    - task: AzureCLI@2
      displayName: 'ACR Login'
      inputs:
        azureSubscription: '$(azureSubscriptionConnectionString)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(acrRegistry)'
    - script: |
        SERVICES=(
          "Catalog/Catalog.API" # Corrected path
          # "Service2" # Replace with your other service names
          # "Service3" # Replace with your other service names
        )
        for SERVICE in "${SERVICES[@]}"; do
          echo "Building Docker image for $SERVICE..."
          dockerfilePath="src/$SERVICE/Dockerfile"
          buildContext="src/$SERVICE"
          imageRepository="amcart.$(echo "$SERVICE" | sed 's/\//./g')" # Replace / with . for image repo name
          docker build -f "$dockerfilePath" -t "$(acrRegistry)/$imageRepository:$(tag)" "$buildContext"
          docker push "$(acrRegistry)/$imageRepository:$(tag)"
        done
      displayName: Build and push multiple images
      env:
        ACR_REGISTRY: '$(acrRegistry)'
        BUILD_TAG: '$(tag)'