trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acrRegistry: 'nagp2024amcart0test0acr.azurecr.io' # Replace with your ACR name #nagp2024amcart0test0acr.azurecr.io    #nagp2024amcart0test0acr0.azurecr.io
  azureSubscriptionConnectionString: 'ServiceConnectionAmcart0Test0' # Replace with your ARM connection name
  serviceImageMappings: 'Services/Catalog/Catalog.API=amcart.catalog.api' # Corrected path

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: BuildImages
    displayName: Build Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'
      inputs:
        dockerVersion: '17.09.0-ce' # Consider using a newer version

    - task: AzureCLI@2
      displayName: 'ACR Login'
      inputs:
        azureSubscription: '$(azureSubscriptionConnectionString)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(acrRegistry)'

    - script: |
        set -x # Enable debugging

        SERVICE="Services/Catalog/Catalog.API"
        IMAGE_NAME="amcart.catalog.api"
        
        dockerfilePath="src/$SERVICE/Dockerfile"
        buildContext="src/$SERVICE"

        # Validate paths
        if [[ ! -f "$dockerfilePath" ]]; then
          echo "Error: Dockerfile not found at $dockerfilePath"
          exit 1
        fi
        if [[ ! -d "$buildContext" ]]; then
          echo "Error: Build context directory not found at $buildContext"
          exit 1
        fi

        # Build and push image
        IMAGE_TAG="$(acrRegistry)/$IMAGE_NAME:$(tag)"
        echo "Building image: $IMAGE_TAG"
        docker build -f "$dockerfilePath" -t "$IMAGE_TAG" "$buildContext"
        docker push "$IMAGE_TAG"
      displayName: Build and Push Catalog.API
      env:
        ACR_REGISTRY: '$(acrRegistry)'
        BUILD_TAG: '$(tag)'
