# Docker - Build multiple Docker images
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acrRegistry: 'nagp2024amcart0test0acr0.azurecr.io' # Replace with your ACR name
  containerRegistryConnectionString: 'ServiceConnectionDockerRegistryAmcart0Test0' # Replace with User-Managed Identity Service Connection
  azureSubscriptionConnectionString: 'ServiceConnectionAmcart0Test0' # Replace with your ARM connection name

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: BuildImages
    displayName: Build Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: AzureCLI@2
      displayName: 'ACR Login'
      inputs:
        azureSubscription: '$(azureSubscriptionConnectionString)' # Replace with your ARM connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(acrRegistry)'
    - script: |
        SERVICES=(
          "Catalog.API"
          "Service2" # Replace with your other service names
          "Service3" # Replace with your other service names
        )
        for SERVICE in "${SERVICES[@]}"; do
          echo "Building Docker image for $SERVICE..."
          dockerfilePath="src/Services/$SERVICE/Dockerfile"
          buildContext="src/Services/$SERVICE"
          imageRepository="amcart.$SERVICE" # Creates unique repo name
          docker build -f "$dockerfilePath" -t "$(acrRegistry)/$imageRepository:$(tag)" "$buildContext"
          docker push "$(acrRegistry)/$imageRepository:$(tag)"
        done
      displayName: Build and push multiple images
      env:
        ACR_REGISTRY: '$(acrRegistry)'
        BUILD_TAG: '$(tag)'