# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acrRegistry: 'nagp2024amcart0test0acr0.azurecr.io' # Replace with your ACR name
  imageRepository: 'amcart.catalog.api' # Replace with your desired image name
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile' # Path to docker file

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'buildAndPush'
        repository: '$(acrRegistry)/$(imageRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: '$(serviceConnecion)' # Replace with your service connection name
        tags: '$(tag)'
        buildContext: '$(Build.SourcesDirectory)' # Set the build context to the root
