# kubectl apply -f catalog-api-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: amcart
type: Opaque
data:
  COSMOSDB_CONNECTION_STRING: bW9uZ29kYjovL2Nvc21vYW1jYXJ0MWNhdGFsb2dkYjE6MGxxZW0wQVhUb05iaXdNanRSTUxMbEVVb0c3VFlZbldONWFyNnhsWXJFNHV4bHhrREZvenhRak56OU9DdE9zTzRvcXZNdVplR25OM0FDRGJIUHZ1ckE9PUBjb3Ntb2FtY2FydDFjYXRhbG9nZGIxLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImcmV0cnl3cml0ZXM9ZmFsc2UmbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AY29zbW9hbWNhcnQxY2F0YWxvZ2RiMUA=
