version: '3.4'

services:
  catalogdb1:
    image: mongo

  # basketdb:
  #   image: redis:alpine

  # discountdb:
  #   image: postgres

  # orderdb:
  #   image: mcr.microsoft.com/mssql/server:2017-latest

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine

  amcart.catalog.api:
    image: ${DOCKER_REGISTRY-}amcart.catalog.api
    build:
      context: .
      # dockerfile: Services/Catalog/Catalog.API/Dockerfile
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      # dockerfile: C:\D\AmCart\src\Services\Catalog\Catalog.API

  # basket.api:
  #   image: ${DOCKER_REGISTRY-}basketapi
  #   build:
  #     context: .
  #     dockerfile: Services/Basket/Basket.API/Dockerfile

  # discount.grpc:
  #   image: ${DOCKER_REGISTRY-}discountgrpc
  #   build:
  #     context: .
  #     dockerfile: Services/Discount/Discount.gRPC/Dockerfile

  # ordering.api:
  #   image: ${DOCKER_REGISTRY-}orderingapi
  #   build:
  #     context: .
  #     dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  # ocelotapigateway:
  #   image: ${DOCKER_REGISTRY-}ocelotapigateway
  #   build:
  #     context: .
  #     dockerfile: APIGateways/OcelotAPIGateway/Dockerfile

  # shopping.aggregator:
  #   image: ${DOCKER_REGISTRY-}shoppingaggregator
  #   build:
  #     context: .
  #     dockerfile: APIGateways/Shopping.Aggregator/Dockerfile
  #pgadmin:
  #  image: dpage/pgadmin4

  #discount.api:
  #  image: ${DOCKER_REGISTRY-}discountapi
  #  build:
  #    context: .
  #    dockerfile: Services/Discount/Discount.API/Dockerfile
  
  #portainer:
  #  image: portainer/portainer-ce


volumes:
   mongo_data:
     # mongodb-catalogdb1:
  #   shared_database:
  #    driver: local

  # postgres_data:
  # pgadmin_data:
  # portainer_data:




